spring.application.name=bookmarkmanager

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration

jwt.secret=${JWT_SECRET:9a3f2d1e4c5b6a7f8e9d0c1b2a3f4e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b0a1f}
jwt.expiration=86400000
